export {default as Header} from './Header'
export {default as Footer} from './Footer'
export {default as Hero} from './Hero'
export {default as WhatWeDo} from './Detail.jsx'
export {default as StudentStoriesSection} from './StudentStories.jsx'
export {default as FinalCTA} from './FinalCta.jsx'
export {default as Card} from './Card.jsx'
export {default as WorriersCard} from './WorriersCard.jsx'